### PR TITLE
Fix travis builds for Python 2.6 in OSX

### PR DESCRIPTION
**Pull request by iamhectorotero**
Travis builds in OSX for Python 2.6 are failing.

~~~~
img2 = scipy.misc.imresize(img, 0.5, interp='bicubic', mode='F')
AttributeError: 'module' object has no attribute 'imresize'
~~~~

### CODE REVIEW

**Comment by Meixu-Chen** [comment]
Thanks for this PR! Travis CI has been replaced by GitHub Actions in v1.1.12, and Python 2.6 is no longer supported (we now test Python 3.10–3.13). Closing as obsolete.
