### ISSUE TITLE
AVConv/AVProbe Warning

### ISSUE THREAD

**Issue by tmatthias29** [scikit-video/scikit-video#44]
This is more of a question than an issue, but if it is a bug, its a _very_ minor one.  After updated to 1.1.8, I see warnings about AVConv/AVProbe not being found in the path, even though FFmpeg _is_ in the path.  My understanding was that sk-video looks for one or the other, but maybe I'm wrong?

**Comment by beyondmetis** [comment]
Hmm, it should not complain about not finding AVConv/AVProbe if it found FFmpeg. This would be a bug :)

**Comment by tmatthias29** [comment]
Hi!  Any estimate on when this changed will be pushed into a release (1.1.9?)?  Thanks!

**Comment by beyondmetis** [comment]
I might push a version when more bugs get fixed. I'll definitely push a version when I provide best-fit curves to the quality estimators.

**Comment by kli017** [comment]
I met the same problem, have you fixed this bug yet?

**Comment by beyondmetis** [comment]
@kli017 If you refer to the warning in this issue, I believe it has been fixed in the repo, but not in the latest release. If this is causing a problem for you, I can release 1.1.9 sooner rather than later.

**Comment by kli017** [comment]
yes i means the warning in this issue. when I use the older version scikit-video I didnt get this warning but an AttributeError: module 'skvideo.io' has no attribute 'vreader'.  later I uninstall the older one and use pip install sk-video I met this warning.  Thanks

**Comment by siarez** [comment]
I installed sk-video(using pip) and ffmpeg(using brew on OSX) today, and also get the same warning upon import.

**Comment by beyondmetis** [comment]
I just updated the release. If you upgrade to 1.1.9, you should see no more warning message
